### ISSUE TITLE
Unhandled Rejection (SyntaxError): Unexpected token P in JSON at position 0

### ISSUE THREAD

**Issue by seenickcode** [ayroblu/ssr-cra-v2.1#4]
Hey there, do you have a sec to look at a crash I'm having?

1. I download the code, run `yarn install`
2. `yarn start`
3. I see the following error (attached)
<img width="945" alt="screen shot 2017-11-02 at 1 58 39 pm" src="https://user-images.githubusercontent.com/75833/32327224-10256f40-bfd6-11e7-950b-194ccef91e5f.png">

I get this in the console:

```
Compiled successfully!

You can now view ssr-cra-v2.1 in the browser.

  Local:            http://localhost:3000/
  On Your Network:  http://192.168.178.38:3000/

Note that the development build is not optimized.
To create a production build, use yarn run build.

Proxy error: Could not proxy request /api from localhost:3000 to http://localhost:3001.
See https://nodejs.org/api/errors.html#errors_common_system_errors for more information (ECONNREFUSED)
```

I'm running node version 9.0.0.

Yet when I run:
```
yarn build
yarn start:prod:server
```

Things work fine.

Any ideas?

Thanks,

**Comment by ayroblu** [comment]
You need a server running in order for requesting things from the server

**Comment by seenickcode** [comment]
See above. Server started per the README.md. Bailing on this anyway, no worries.
