### ISSUE TITLE
SSR identify if bot or actual user

### ISSUE THREAD

**Issue by eranhirs** [ayroblu/ssr-cra-v2.1#5]
First of all, thanks for these awesome articles!

Since the loading time is pretty slow for my users, I would like to prefetch data only if it's a google crawling bot, and for the users I prefer a lazy loading.

What's the best way to check if it's a bot or not?

Thanks!

**Comment by ayroblu** [comment]
You can take a look at a user agent parser, that's probably the easiest way

**Comment by eranhirs** [comment]
I understand you can also choose to cache the HTML as a good alternative, what's your preferred tool?
